
-- Create services table
CREATE TABLE IF NOT EXISTS public.services (
    id bigint generated by default as identity primary key,
    name text not null,
    price numeric not null,
    duration_minutes integer not null,
    master_id text, -- Stores telegram_id of the barber, or null if global
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Policy
DROP POLICY IF EXISTS "Enable access for all users" ON public.services;
CREATE POLICY "Enable access for all users" ON public.services
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Insert initial data from JSON (optional, but good for starting)
-- We will do this via python script migration, but good to have table ready.
